site_name: Trabajando con VT
theme:
  name: 'material'
  language: 'es'
markdown_extensions:
  - codehilite:
      linenums: True
  - admonition
  - pymdownx.magiclink
  - pymdownx.superfences
repo_url: "https://github.com/geoinquiets/taller-vt"
nav:
- Home: index.md
- 1. Qué son: 1_teoria.md
- 2. Cómo visualizarlas: 2_visor_simple.md
- 3. Cómo servirlas: 3_tileserver_gl.md
- 4. Cómo crearlas: 4_tippecanoe.md
- 5. Sprites y Glyphs: 5_sprites_glyphs.md
- 6. Cómo simbolizarlas: 6_estilos.md
- 7. Cómo servir datos dinámicos: 7_servidor_dinamico.md
- 8. Cómo servir datos desde PostGIS: 8_postgis_vt.md
- 9. Servir vector tiles desde GeoServer: 9_geoserver_vts.md
